// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8c9oDWVNND0mM2UCy1nvK-QP11ltMskE',
    appId: '1:730271059087:web:f07e1e3c59a187207df4fa',
    messagingSenderId: '730271059087',
    projectId: 'mad-poject',
    authDomain: 'mad-poject.firebaseapp.com',
    storageBucket: 'mad-poject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGVWQ69hPuAO21NN30-xOiCxgXJ_h4oLA',
    appId: '1:730271059087:android:97cfe362967aa26e7df4fa',
    messagingSenderId: '730271059087',
    projectId: 'mad-poject',
    storageBucket: 'mad-poject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwDnggu6f1X17bYSnWu1sZefbeuURmN-I',
    appId: '1:730271059087:ios:afedb52cae8b9c177df4fa',
    messagingSenderId: '730271059087',
    projectId: 'mad-poject',
    storageBucket: 'mad-poject.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwDnggu6f1X17bYSnWu1sZefbeuURmN-I',
    appId: '1:730271059087:ios:35b7608050f5f5e67df4fa',
    messagingSenderId: '730271059087',
    projectId: 'mad-poject',
    storageBucket: 'mad-poject.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
